version: '3.1'

services:

  db:
    ports:
    - "5432:5432"
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    volumes:
    #mapping the db path to the host folder
    - ./db/data:/var/lib/postgresql/data
    - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d